### ISSUE TITLE
unable to create a patch

### ISSUE THREAD

**Issue by TonyTheFerg** [paragdiwan/vscode-git-patch#15]
trying to create patches, `test.patch` whether staged or not does not work. Are there things I need to do to set it up properly?

**Comment by paragdiwan** [comment]
@TonyTheFerg Thanks for tring git-patch.  Let me know below , I will help you to sort out the issue

1. Current OS 
2. `GIT` installed ?

**Comment by dfleitascds** [comment]
Same issue here. MacOS Big Sur 11.6
git version 2.30.1 (Apple Git-130)

**Comment by DiegoFleitas** [comment]
Same issue here. MacOS Big Sur 11.6
git version 2.30.1 (Apple Git-130)

**Comment by TonyTheFerg** [comment]
@paragdiwan WSL2, and git 2.25.1

**Comment by TonyTheFerg** [comment]
Seems to be working now. :)

**Comment by paragdiwan** [comment]
Closing this issue as it's working.
