### ISSUE TITLE
Unable to create a patch with a non-alphanumeric patch name.

### ISSUE THREAD

**Issue by bayu01** [paragdiwan/vscode-git-patch#7]
Hello,  when I attempt to create a patch using a patch name that contains spaces, I get 
![image](https://user-images.githubusercontent.com/6752227/42380232-cc0cc770-80f2-11e8-9dde-b0a735d3ebdb.png). It just creates an empty file with a truncated name.

For example, attempting to create a patch using _test patch_ as the name, just creates an empty file with the name _test_.

**Comment by paragdiwan** [comment]
The filename should not have special characters
